"""
Django settings for Cangshuge project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from etcd.client import Client
import pymysql
pymysql.install_as_MySQLdb()


ETCD_HOST = os.environ['EV_ETCD_HOST']
ETCD_PORT = int(os.environ['EV_ETCD_PORT'])
ETCD_USERNAME = os.environ.get('EV_ETCD_USERNAME')
ETCD_PASSWORD = os.environ.get('EV_ETCD_PASSWORD')
ETCD_CLIENT = Client(
    host=ETCD_HOST,
    port=ETCD_PORT,
    username=ETCD_USERNAME,
    password=ETCD_PASSWORD,
    allow_redirect=False
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd512q-h72nx@g33l24pekc+swopr%*xqo8w$vtvtv0&s0hat9s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEBUG = False

ALLOWED_HOSTS = ['laowangkanti.abraham.science']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'question_viewer'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Cangshuge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Cangshuge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DB_CONFIG_DICT = {}

# 此项目为线下服务，只需要读取线下的题库数据库即可
question_offline_db_value = ETCD_CLIENT.get(
    '/db/question_pre_db',
)
print(question_offline_db_value)
DB_CONFIG_DICT['question_offline_db'] = eval(
    question_offline_db_value.value
)
assert DB_CONFIG_DICT['question_offline_db']['host'] == '10.44.149.251'
DB_CONFIG_DICT['question_offline_db']['db'] = 'question_db_offline'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'question_offline_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_CONFIG_DICT['question_offline_db']['db'],
        'USER': DB_CONFIG_DICT['question_offline_db']['user'],
        'PASSWORD': DB_CONFIG_DICT['question_offline_db']['passwd'],
        'HOST': DB_CONFIG_DICT['question_offline_db']['host'],
        'PORT': DB_CONFIG_DICT['question_offline_db']['port'],

    }
}


DATABASE_ROUTERS = ['conf.db_router.QuestionOfflineRouter']

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# session 
SESSION_COOKIE_AGE = 60 * 60 * 18


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = 'static'
STATICFILES_DIRS = [
   os.path.join(BASE_DIR, "static"),
]
from Cangshuge.authenticate import *
